### ISSUE TITLE
Move from parse.com

### ISSUE THREAD

**Issue by exalted** [exalted/Yeni1Tarif#9]
## To-dos
- [x] Read https://github.com/ParsePlatform/parse-server/wiki/Compatibility-with-Hosted-Parse
- [x] Move app to self-hosted Parse server
- [x] Move yeni1tarif app (web2cloud) on heroku to point to self-hosted Parse server
## Consider
- ~~[CloudKit](https://developer.apple.com/library/ios/technotes/tn2241/_index.html)~~
## Migration Notes/Guides
- https://parse.com/migration
- https://blog.heroku.com/archives/2016/2/4/running-parse-on-heroku --> https://devcenter.heroku.com/articles/deploying-a-parse-server-to-heroku
- https://github.com/ParsePlatform/parse-server/wiki#community-links
- https://natanrolnik.me/2016/03/31/migrating-my-data-from-parse/
- https://www.raywenderlich.com/128313/parse-server-tutorial
- http://www.appcoda.com/parse-server-installation/
### Proxy
- https://github.com/ParsePlatform/parse-server/issues/137
- https://blog.heroku.com/how-belly-scales-using-api-proxies-with-their-microservices-architecture
- http://feedproxy.google.com/~r/heroku/~3/Vj6hEgby4xo/using_netflix_zuul_to_proxy_your_microservices
